TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this

# Install ADStream db files
DB_INSTALLS += $(wildcard $(ADSTREAM)/db/*.db)

# Install ADStream cmd scripts
DB_INSTALLS += $(wildcard $(ADSTREAM)/db/*.cmd)

#----------------------------------------------------
# Create and install (or just install)
# Archive files, templates, substitutions like this
#

#----------------------------------------------------
# Create and install (or just install)
# Autosave request files, templates, substitutions like this
#

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

